# Generated by Django 5.2.11 on 2026-02-10 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('market', models.CharField(choices=[('KR', 'Korea'), ('US', 'USA')], max_length=2)),
                ('sector', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traded_at', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('volume', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock')),
            ],
            options={
                'ordering': ['-traded_at', '-id'],
                'indexes': [models.Index(fields=['traded_at'], name='stocks_pric_traded__587c48_idx')],
                'unique_together': {('stock', 'traded_at')},
            },
        ),
        migrations.CreateModel(
            name='Buzz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('twitter', 'Twitter'), ('naver', 'Naver'), ('news', 'News')], max_length=16)),
                ('recorded_at', models.DateTimeField()),
                ('mentions', models.PositiveIntegerField(default=0)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzz_records', to='stocks.stock')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['recorded_at', 'source'], name='stocks_buzz_recorde_b89870_idx')],
            },
        ),
    ]
