# Generated by Django 5.2.11 on 2026-02-11 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buzz',
            new_name='Interest',
        ),
        migrations.AlterField(
            model_name='interest',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_records', to='stocks.stock'),
        ),
    ]
