# Generated by Django 5.2.11 on 2026-02-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_interest_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='interest',
            new_name='stocks_inte_recorde_9ab332_idx',
            old_name='stocks_buzz_recorde_b89870_idx',
        ),
    ]
