# Generated by Django 5.2.11 on 2026-02-11 03:53

from django.db import migrations, models


def migrate_twitter_to_news(apps, schema_editor):
    Interest = apps.get_model("stocks", "Interest")
    Interest.objects.filter(source="twitter").update(source="news")


def reverse_migrate_twitter_to_news(apps, schema_editor):
    # 원복 시점에는 source 구분 정보를 잃으므로 no-op 처리
    return


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_rename_stocks_buzz_recorde_b89870_idx_stocks_inte_recorde_9ab332_idx'),
    ]

    operations = [
        migrations.RunPython(
            migrate_twitter_to_news,
            reverse_code=reverse_migrate_twitter_to_news,
        ),
        migrations.AlterField(
            model_name='interest',
            name='source',
            field=models.CharField(choices=[('reddit', 'Reddit'), ('naver', 'Naver'), ('news', 'News')], max_length=16),
        ),
    ]
