# Generated by Django 5.2.11 on 2026-02-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_interest_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('news', 'News')], default='news', max_length=16)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=120)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='stocks.stock')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['stock', 'published_at'], name='stocks_news_stock_i_4f9e6e_idx'), models.Index(fields=['source', 'published_at'], name='stocks_news_source_5af178_idx')],
                'unique_together': {('stock', 'url')},
            },
        ),
    ]
