# Generated by Django 5.2.11 on 2026-02-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('discussed_symbols', models.JSONField(blank=True, default=list)),
                ('generated_by', models.CharField(default='openai', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-briefing_date', '-id'],
            },
        ),
    ]
