# Generated by Django 5.2.11 on 2026-02-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybriefing',
            name='generated_by',
            field=models.CharField(default='gemini', max_length=32),
        ),
    ]
