# Generated by Django 5.2.11 on 2026-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0002_alter_dailybriefing_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybriefing',
            name='email_failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailybriefing',
            name='email_recipient_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailybriefing',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailybriefing',
            name='email_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16),
        ),
    ]
